const palette = {
  primary: {
    o0: 'var(--color-primary-o0)',
    o1: 'var(--color-primary-o1)',
    o2: 'var(--color-primary-o2)',
    o3: 'var(--color-primary-o3)',
  },
  status: {
    error: 'var(--color-status-error)',
    warning: 'var(--color-status-warning)',
    success: 'var(--color-status-success)',
    link: 'var(--color-status-link)',
  },
  purple: {
    main: 'var(--color-purple-main)',
    sub: 'var(--color-purple-sub)',
  },
  blue: {
    main: 'var(--color-blue-main)',
    sub: 'var(--color-blue-sub)',
  },
  green: {
    main: 'var(--color-green-main)',
    sub: 'var(--color-green-sub)',
  },
  red: {
    main: 'var(--color-red-main)',
    sub: 'var(--color-red-sub)',
  },
  yellow: {
    main: 'var(--color-yellow-main)',
    sub: 'var(--color-yellow-sub)',
  },
  grey: {
    main: 'var(--color-grey-main)',
    sub: 'var(--color-grey-sub)',
    w: 'var(--color-grey-w)',
    g00: 'var(--color-grey-g00)',
    g10: 'var(--color-grey-g10)',
    g20: 'var(--color-grey-g20)',
    g30: 'var(--color-grey-g30)',
    g40: 'var(--color-grey-g40)',
    g50: 'var(--color-grey-g50)',
    g60: 'var(--color-grey-g60)',
    g70: 'var(--color-grey-g70)',
    g80: 'var(--color-grey-g80)',
    g90: 'var(--color-grey-g90)',
    g100: 'var(--color-grey-g100)',
    b: 'var(--color-grey-b)',
  },
  dim: {
    dialog: 'var(--color-dim-dialog)',
  },
  shadow: 'var(--color-shadow)',
  mobile: {
    primary: {
      o1: 'var(--color-mobile-primary-o1)',
    },
    status: {
      error: 'var(--color-mobile-status-error)',
      success: 'var(--color-mobile-status-success)',
    },
    grey: {
      w: 'var(--color-mobile-grey-w)',
      g05: 'var(--color-mobile-grey-g05)',
      g10: 'var(--color-mobile-grey-g10)',
      g15: 'var(--color-mobile-grey-g15)',
      g20: 'var(--color-mobile-grey-g20)',
      g30: 'var(--color-mobile-grey-g30)',
      g40: 'var(--color-mobile-grey-g40)',
      g50: 'var(--color-mobile-grey-g50)',
      g60: 'var(--color-mobile-grey-g60)',
      g70: 'var(--color-mobile-grey-g70)',
      g80: 'var(--color-mobile-grey-g80)',
      g85: 'var(--color-mobile-grey-g85)',
      g90: 'var(--color-mobile-grey-g90)',
      g95: 'var(--color-mobile-grey-g95)',
      b: 'var(--color-mobile-grey-b)',
    },
  },
  opacity: {
    0: '00',
    5: '0C',
    10: '19',
    15: '26',
    20: '33',
    25: '3F',
    30: '4C',
    35: '59',
    40: '66',
    45: '72',
    50: '7F',
    55: '8C',
    60: '99',
    65: 'A5',
    70: 'B2',
    75: 'BF',
    80: 'CC',
    85: 'D8',
    90: 'E5',
    95: 'F2',
    100: 'FF',
  },
} as const;

export default palette;
